### ISSUE TITLE
Building Docker image

### ISSUE THREAD

**Issue by farheen-akhter-code** [DrAlzahraniProjects/csusb_fall2024_cse6550_team2#27]
@ketha-shishir I have taken latest pull from main branch and observed while I am trying to build docker image , mamba installation takes huge time , to which I am not able to build image yet.

Below is the screenshot showing time taking to build image 
![image](https://github.com/user-attachments/assets/06983a86-30db-40fe-bb2c-703a3fb22d75)

Please see if we can minimize the mamba installation time. 

Now that it is completed i get an error in windows machine, below is the screenshot for the same
![image](https://github.com/user-attachments/assets/6f7842f6-7632-4783-983c-eee412218811)

**Comment by ketha-shishir** [comment]
@farheen-akhter-code the build is working but I understand it is taking a lot of time. I'll work on it.

**Comment by Arungodugu** [comment]
@ketha-shishir I’ve pulled the latest changes from the main branch and was able to successfully build the Docker image on my Windows machine. The Mamba installation completed without any major delays.

Here’s a screenshot of the build working on my end:
![Screenshot 2024-09-12 145707](https://github.com/user-attachments/assets/71d1c854-681e-42f3-902a-330c59f8609e)

**Comment by Prasanth-Kandikatla** [comment]
No major delays for me as well!
Ran in Windows 11

**Comment by farheen-akhter-code** [comment]
> @farheen-akhter-code the build is working but I understand it is taking a lot of time. I'll work on it.

Can you specify steps you followed along to build docker image ?

**Comment by farheen-akhter-code** [comment]
@ketha-shishir I am able to build the image and run it now . It took me long like a day , but I constantly restarted the system so the process of build was fast. But we need to work out way to reduce build time . Here is the screenshot of the loading app. 
![image](https://github.com/user-attachments/assets/4b6c4057-40b9-439e-818f-ff94d9903190)
